/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final;

import static java.lang.String.valueOf;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brayan Cifuentes
 */
public class Carreras extends javax.swing.JInternalFrame {

    /**
     * Creates new form Empleados
     */
    String BD = "jdbc:mysql://localhost/siu";
    String Usuario = "root";
    String Clave = "Cagada1234";

    public Carreras() {
        initComponents();

        //llamar en el constructor el metodo
        consultar_cbx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_idcarrera = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_estatus = new javax.swing.JTextField();
        cbx_facultad = new javax.swing.JComboBox<>();
        lbl_codigofac = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_carrera = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Carreras");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Carrera:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, -1, -1));

        txt_nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 211, 111, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre Carrera:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 213, -1, -1));

        txt_idcarrera.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_idcarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idcarreraActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 173, 111, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Codigo Facultad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 253, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ingresa el código del carrera: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 13, -1, -1));

        txt_buscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 520, 30));

        jButton4.setBackground(new java.awt.Color(141, 141, 208));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busquedap.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 23, 60, 50));

        jButton1.setBackground(new java.awt.Color(141, 141, 208));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardarp.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 83, 60, 50));

        jButton2.setBackground(new java.awt.Color(141, 141, 208));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 83, 60, 50));

        jButton3.setBackground(new java.awt.Color(141, 141, 208));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 83, 70, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Estatus Carrera");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 295, -1, -1));

        txt_estatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estatusActionPerformed(evt);
            }
        });
        getContentPane().add(txt_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 295, 111, -1));

        cbx_facultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_facultadMouseClicked(evt);
            }
        });
        cbx_facultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_facultadActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_facultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 254, 111, -1));

        lbl_codigofac.setText("Codigo ");
        getContentPane().add(lbl_codigofac, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 261, 57, -1));

        tbl_carrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Carrera", "Nombre Carrera", "Codigo Facultad", "Estatus Carrera"
            }
        ));
        tbl_carrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_carreraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_carrera);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 158, -1, 111));

        jButton5.setText("Listar Datos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 288, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("                        Para modificar:\n1. Debe buscar el codigo de la carrera\n2. Luego seleccionar la fila de la tabla \n3. Modificar los campos necesarios\n4. Darle click al boton Modificar (Icono del \n    Lápiz).");
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 275, 350, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void consultar_cbx() {
        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);
            PreparedStatement pst = cn.prepareStatement("select nombre_facultad from facultades");

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            cbx_facultad.addItem("Facultad");

            while (rs.next()) {
                cbx_facultad.addItem(rs.getString("nombre_facultad"));
            }

            rs.close();

        } catch (Exception e) {

        }
    }

    public void Tabla() {
        try {

            Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);

            PreparedStatement ps = cn.prepareStatement("select * from carreras");
            PreparedStatement ps2 = cn.prepareStatement("select * from carreras");
            //pstt4.setString(1, txt_buscar.getText().trim());

            ResultSet rs = ps.executeQuery();

            ResultSet rss = ps2.executeQuery();

            if (rs.next()) {

                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("codigo_carrera");
                modelo.addColumn("nombre_carrera");
                modelo.addColumn("codigo_facultad");
                modelo.addColumn("estatus_carrera");

                tbl_carrera.setModel(modelo);

                String[] dato = new String[4];

                while (rss.next()) {
                    dato[0] = rss.getString(1);
                    dato[1] = rss.getString(2);
                    dato[2] = rss.getString(3);
                    dato[3] = rss.getString(4);
                    modelo.addRow(dato);

                }
            }

        } catch (Exception e) {

        }
    }

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_idcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idcarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idcarreraActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//Codigo que permite consultar registros en la base de datos
        
        try {

            Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);

            PreparedStatement pstt4 = cn.prepareStatement("select * from carreras where codigo_carrera=?");
            pstt4.setString(1, txt_buscar.getText().trim());

            ResultSet rss4 = pstt4.executeQuery();

            // hacer la copia del query para que la tabla empiece desde 1
            PreparedStatement ps = cn.prepareStatement("select * from carreras where codigo_carrera=?");
            ps.setString(1, txt_buscar.getText().trim());

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {

                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("codigo_carrera");
                modelo.addColumn("nombre_carrera");
                modelo.addColumn("codigo_facultad");
                modelo.addColumn("estatus_carrera");

                tbl_carrera.setModel(modelo);

                String[] dato = new String[4];

                while (rss4.next()) {
                    dato[0] = rss4.getString(1);
                    dato[1] = rss4.getString(2);
                    dato[2] = rss4.getString(3);
                    dato[3] = rss4.getString(4);
                    modelo.addRow(dato);

                }
            } else {
                JOptionPane.showMessageDialog(null, "Carrera no Registrada");
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Codigo que permite insertar registros en al base de datos
        try {
Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);
            PreparedStatement pst = cn.prepareStatement("insert into carreras values(?,?,?,?)");

            pst.setString(1, txt_idcarrera.getText().trim());
            pst.setString(2, txt_nombre.getText().trim());
            pst.setString(3, lbl_codigofac.getText().trim());
            pst.setString(4, txt_estatus.getText().trim());

            pst.executeUpdate();

            txt_idcarrera.setText("");
            txt_nombre.setText("");
            lbl_codigofac.setText("");
            txt_estatus.setText("");

            //regresa ala primera opcion del combobox
            cbx_facultad.setSelectedIndex(0);

            JOptionPane.showMessageDialog(this, "¡REGISTRO EXITOSO!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            Tabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en registro", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//Codigo que permite modificar registros en la base de datos
        try {
            String ID = txt_idcarrera.getText().trim();

            Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);
            PreparedStatement pst = cn.prepareStatement("update carreras set codigo_carrera = ?, nombre_carrera=?, codigo_facultad=?, estatus_carrera=? where codigo_carrera = " + ID);

            pst.setString(1, txt_idcarrera.getText().trim());
            pst.setString(2, txt_nombre.getText().trim());
            pst.setString(3, lbl_codigofac.getText().trim());
            pst.setString(4, txt_estatus.getText().trim());

            pst.executeUpdate();

            txt_idcarrera.setText("");
            txt_nombre.setText("");
            lbl_codigofac.setText("");
            txt_estatus.setText("");

            JOptionPane.showMessageDialog(this, "¡MODIFICACION EXITOSA!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            Tabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en modificación", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//Codigo que permite borrar registros en la base de datos
        try {

            Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);
            PreparedStatement pst = cn.prepareStatement("delete from carreras where codigo_carrera = ?");

            pst.setString(1, txt_idcarrera.getText().trim());
            pst.executeUpdate();

            txt_idcarrera.setText("");
            txt_nombre.setText("");
            lbl_codigofac.setText("");
            txt_estatus.setText("");

            JOptionPane.showMessageDialog(this, "¡ELIMINACION EXITOSA!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            
            Tabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en eliminación", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estatusActionPerformed

    private void cbx_facultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_facultadMouseClicked
    }//GEN-LAST:event_cbx_facultadMouseClicked

    private void cbx_facultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_facultadActionPerformed
        // TODO add your handling code here:
        try {
          Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);
            PreparedStatement pst = cn.prepareStatement("select codigo_facultad from facultades where nombre_facultad=?");
            pst.setString(1, cbx_facultad.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            //cbx_facultad.addItem("Facultad");
            if (rs.next()) {
                lbl_codigofac.setText(rs.getString("codigo_facultad"));
            }

            //rs.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbx_facultadActionPerformed

    private void tbl_carreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_carreraMouseClicked
        // TODO add your handling code here:
        //para seleccionar el dato y mostrarlo en los txt
        int seleccionar = tbl_carrera.rowAtPoint(evt.getPoint());
        txt_idcarrera.setText(String.valueOf(tbl_carrera.getValueAt(seleccionar, 0)));
        txt_nombre.setText(String.valueOf(tbl_carrera.getValueAt(seleccionar, 1)));
        lbl_codigofac.setText(valueOf(tbl_carrera.getValueAt(seleccionar, 2)));
        txt_estatus.setText(String.valueOf(tbl_carrera.getValueAt(seleccionar, 3)));
        
        try {
          Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);
            PreparedStatement pst = cn.prepareStatement("select nombre_facultad from facultades where codigo_facultad=?;");
            pst.setString(1, lbl_codigofac.getText());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cbx_facultad.setSelectedItem(rs.getString("nombre_facultad"));
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_tbl_carreraMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Tabla();
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_facultad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_codigofac;
    private javax.swing.JTable tbl_carrera;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_estatus;
    private javax.swing.JTextField txt_idcarrera;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
