/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sucely Alvarez
 */
public class Consulta_notas extends javax.swing.JInternalFrame {

    String BD = "jdbc:mysql://localhost/siu";
    String Usuario = "root";
    String Clave = "Cagada1234";

    /**
     * Creates new form Consulta_notas
     */
    public Consulta_notas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void totalizar(){
        double t=0;
        double p=0;
        if(Tbl_notas.getRowCount()>0){
            for(int i=0;i<Tbl_notas.getRowCount();i++){
                p=Double.parseDouble(Tbl_notas.getValueAt(i,2).toString());
                t+=p;
            }
            lbl_total.setText(String.valueOf(t));
        }
        else{
            JOptionPane.showMessageDialog(null, "");
        }
    }
    
     public void cbx_curso() {
        //Codigo que permite consultar registros en la base de datos
        try {
        Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);
            PreparedStatement pst = cn.prepareStatement("select distinct codigo_curso from asignacioncursosalumnos");

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            cbx_curso.addItem("Cursos");

            while (rs.next()) {
                cbx_curso.addItem(rs.getString("codigo_curso"));
            }

            rs.close();

        } catch (Exception e) {

        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_notas = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        cbx_curso = new javax.swing.JComboBox<>();
        lbl_nombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consulta Notas");
        setVisible(true);

        txtBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese su número de carnet");

        Tbl_notas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Curso", "Tipo Nota", "Nota"
            }
        ));
        Tbl_notas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_notasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_notas);

        jButton4.setBackground(new java.awt.Color(141, 141, 208));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busquedap.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cbx_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cursoActionPerformed(evt);
            }
        });

        lbl_nombre.setText("Nombre");

        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Nota:");

        lbl_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_total.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbx_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_nombre)
                        .addGap(73, 73, 73)
                        .addComponent(jButton1)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(lbl_total))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lbl_total))))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tbl_notasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_notasMouseClicked

    }//GEN-LAST:event_Tbl_notasMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        cbx_curso.removeAllItems();
        cbx_curso();
        /*        try {
            String ID = txtBuscar.getText();

            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pstt4 = cn.prepareStatement("select * from notas where carnet_alumno = " + ID);
            ResultSet rss4 = pstt4.executeQuery();

            PreparedStatement pstt = cn.prepareStatement("select * from notas where carnet_alumno = " + ID);
            ResultSet rss = pstt.executeQuery();
            if (rss.next()) {
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.addColumn("codigo_notas");
                modelo.addColumn("carnet_alumno");
                modelo.addColumn("codigo_curso");
                modelo.addColumn("nombre_curso");
                modelo.addColumn("tipo_nota");
                modelo.addColumn("nota");

                Tbl_notas.setModel(modelo);
                String[] dato = new String[6];
                while (rss4.next()) {
                    dato[0] = rss4.getString(1);
                    dato[1] = rss4.getString(2);
                    dato[2] = rss4.getString(3);
                    dato[3] = rss4.getString(4);
                    dato[4] = rss4.getString(5);
                    dato[5] = rss4.getString(6);

                    modelo.addRow(dato);
                }
            }
            else{
                  JOptionPane.showMessageDialog(null, "El codigo de estudiante no existe");
                   }

        } catch (Exception e) {

        }*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbx_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cursoActionPerformed
        
        try {
           Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);
            PreparedStatement pst = cn.prepareStatement("select nombre_curso from cursos where codigo_curso=?;");
            pst.setString(1, cbx_curso.getSelectedItem().toString());
           // pst.setString(2, txtBuscar.getText().trim());
            

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentario
            //cbx_curso.addItem("Curso");
            
            if (rs.next()) {
                lbl_nombre.setText(rs.getString("nombre_curso"));
            }

            rs.close();
            
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbx_cursoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            //String ID1 = cbx_curso.getSelectedItem().toString();
            //String ID2 = txtBuscar.getText().trim();
            
            Connection cn = DriverManager.getConnection(mdiVentana.BD, mdiVentana.Usuario, mdiVentana.Contraseña);
            PreparedStatement pstt4 = cn.prepareStatement("select codigo_curso, tipo_nota, nota_asignacioncursoalumnos from asignacioncursosalumnos where carnet_alumno=? and codigo_curso=?");
            pstt4.setString(1, txtBuscar.getText().trim());
            pstt4.setString(2, cbx_curso.getSelectedItem().toString());
            
            ResultSet rss4 = pstt4.executeQuery();

            PreparedStatement pstt = cn.prepareStatement("select codigo_curso, tipo_nota, nota_asignacioncursoalumnos from asignacioncursosalumnos where carnet_alumno=? and codigo_curso=?");
            pstt.setString(1, txtBuscar.getText().trim());
            pstt.setString(2, cbx_curso.getSelectedItem().toString());
            
            ResultSet rss = pstt.executeQuery();
            if (rss.next()) 
            {
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.addColumn("codigo_curso");
                modelo.addColumn("tipo_nota");
                modelo.addColumn("nota_asignacioncursoalumnos");

                Tbl_notas.setModel(modelo);
                String[] dato = new String[3];
                
                while (rss4.next()) {
                    dato[0] = rss4.getString(1);
                    dato[1] = rss4.getString(2);
                    dato[2] = rss4.getString(3);
                    

                    modelo.addRow(dato);
                }
            }
            else{
                  JOptionPane.showMessageDialog(null, "El codigo de estudiante no existe");
                   }

        } catch (Exception e) {

        }
        
        totalizar();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbl_notas;
    private javax.swing.JComboBox<String> cbx_curso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
